In [2]:
import tensorflow as tf
import dataset

In [8]:
a = tf.truncated_normal([16,128,128,3])
sess = tf.Session()
sess.run(tf.initialize_all_variables())
sess.run(tf.shape(a))

array([ 16, 128, 128,   3])

In [9]:
b=tf.reshape(a,[16,49152])
sess.run(tf.shape(b))

array([   16, 49152])

In [10]:
x = [0., -1., 2., 3.]
softmax_x = tf.nn.softmax(x)
print(x)
print("SOFTMAX X")
print(sess.run(softmax_x))

[0.0, -1.0, 2.0, 3.0]
SOFTMAX X
[0.03467109 0.01275478 0.25618663 0.69638747]


In [11]:
pwd


'C:\\Users\\HAI'

In [3]:
classes = ['dogs', 'cats']
num_classes = len(classes)
 
train_path='train'
 
# validation split
validation_size = 0.2
 
# batch size
batch_size = 16
 
data = dataset.read_train_sets(train_path, img_size, classes, validation_size=validation_size)


AttributeError: module 'dataset' has no attribute 'read_train_sets'

In [14]:
from keras.models import Sequential

Using TensorFlow backend.


In [15]:
from keras.layers import Convolution2D

In [16]:
from keras.layers import MaxPooling2D

In [17]:
from keras.layers import Flatten

In [18]:
from keras.layers import Dense

In [19]:
classifier=Sequential()
classifier.add(Convolution2D(32,(3,3),input_shape=(64,64,3),activation='relu'))

Instructions for updating:
Colocations handled automatically by placer.


In [20]:
classifier.add(MaxPooling2D(pool_size=(2,2)))

In [21]:
classifier.add(Flatten())

In [22]:
classifier.add(Dense(units=128,activation='relu'))

In [23]:
classifier.add(Dense(units=1,activation='sigmoid'))

In [24]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [25]:
from keras.preprocessing.image import ImageDataGenerator

In [26]:
train_datagen=ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

In [27]:
test_datagen=ImageDataGenerator(rescale=1./255)

In [28]:
training_set=train_datagen.flow_from_directory(
    'dataset/training_set',
    target_size=(64,64),
    batch_size=32,
    class_mode='binary')

Found 8000 images belonging to 2 classes.


In [29]:
test_set=test_datagen.flow_from_directory(
    'dataset/test_set',
    target_size=(64,64),
    batch_size=32,
    class_mode='binary')

Found 2000 images belonging to 2 classes.


In [30]:
from IPython.display import display

In [31]:
from PIL import Image

In [32]:
classifier.fit_generator(training_set,steps_per_epoch=320,epochs=10,validation_data=test_set,validation_steps=800)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
319/320 [============================>.] - ETA: 0s - loss: 0.6901 - acc: 0.6143

KeyboardInterrupt: 

In [226]:
import numpy as np


In [215]:
from keras.preprocessing import image

In [232]:
test_im=image.load_img('random.jpeg',target_size=(64,64))

In [233]:
test_im=image.img_to_array(test_im)

In [234]:
test_im=np.expand_dims(test_im,axis=0)

In [235]:
result=classifier.predict_proba(test_im)
print(result)

[[1.]]


In [236]:
training_set.class_indices

{'cats': 0, 'dogs': 1}

In [237]:
if result[0][0]>=0.5:
    prediction='dog'
else:
    prediction='cat'
print(result[0][0])

1.0


In [238]:
print(prediction)

dog


In [239]:
test_ima=image.load_img('rand2.jpg',target_size=(64,64))

In [240]:
test_ima=image.img_to_array(test_ima)
test_ima=np.expand_dims(test_ima,axis=0)

In [241]:
resultt=classifier.predict_proba(test_ima)
print(resultt)

[[1.]]


In [242]:
training_set.class_indices

{'cats': 0, 'dogs': 1}

In [243]:
if resultt[0][0]>=0.5:
    prediction='dog'
else:
    prediction='cat'
print(resultt[0][0])

1.0


In [244]:
print(prediction)

dog


In [263]:
test_image=image.load_img('krishna.jpg',target_size=(64,64))

In [264]:
test_image=image.img_to_array(test_image)
test_image=np.expand_dims(test_image,axis=0)

In [265]:
resultkrishna=classifier.predict_proba(test_image)
print(resultkrishna)

[[0.]]


In [266]:
test_image=image.load_img('krishnacat.jpg',target_size=(64,64))

In [267]:
test_image=image.img_to_array(test_image)
test_image=np.expand_dims(test_image,axis=0)

In [268]:
resultkrishna=classifier.predict(test_image)
print(resultkrishna)

[[1.]]


In [269]:
test_image2=image.load_img('krishnadog.jpg',target_size=(64,64))

In [270]:
test_image2=image.img_to_array(test_image2)
test_image2=np.expand_dims(test_image2,axis=0)

In [271]:
res=classifier.predict(test_image2)
print(res)

[[1.]]


In [272]:
test_image3=image.load_img('krishnacat.jpg',target_size=(64,64))

In [273]:
test_image3=image.img_to_array(test_image3)
test_image3=np.expand_dims(test_image3,axis=0)

In [274]:
resu=classifier.predict(test_image3)
print(resu)

[[1.]]


In [284]:
test_image4=image.load_img('krishnaaa.jpg',target_size=(64,64))

In [285]:
test_image4=image.img_to_array(test_image4)
test_image4=np.expand_dims(test_image4,axis=0)

In [286]:
resul=classifier.predict(test_image4)
print(resu)

[[1.]]


In [287]:
test_image5=image.load_img('krishna.jpg',target_size=(64,64))

In [288]:
test_image5=image.img_to_array(test_image5)
test_image5=np.expand_dims(test_image5,axis=0)

In [289]:
resultkrish=classifier.predict_proba(test_image5)
print(resultkrish)

[[0.]]


In [290]:
test_image6=image.load_img('rama.jpg',target_size=(64,64))

In [291]:
test_image6=image.img_to_array(test_image6)
test_image6=np.expand_dims(test_image6,axis=0)

In [283]:
resultram=classifier.predict_proba(test_image6)
print(resultram)

[[0.]]
