In [0]:
import tensorflow as tf
import dataset

In [0]:
from google.colab import drive,files

In [63]:
!pip install dataset

     |████████████████████████████████| 1.0MB 5.1MB/s 
     |████████████████████████████████| 471kB 44.9MB/s 
  Stored in directory: /root/.cache/pip/wheels/de/cf/b3/0eb5c89ea6aa1b49cb41315f9ec139ada8cbffd575bf170d43
  Stored in directory: /root/.cache/pip/wheels/b4/cb/4b/b64eabdf5c11ecb491a37c72819148976f276d323ca12bcaf4
Successfully built alembic Mako


In [0]:
pwd


'/content'

In [66]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
import dataset

In [68]:
a = tf.truncated_normal([16,128,128,3])
sess = tf.Session()
sess.run(tf.initialize_all_variables())
sess.run(tf.shape(a))

array([ 16, 128, 128,   3], dtype=int32)

In [69]:
b=tf.reshape(a,[16,49152])
sess.run(tf.shape(b))

array([   16, 49152], dtype=int32)

In [70]:
x = [0., -1., 2., 3.]
softmax_x = tf.nn.softmax(x)
print(x)
print("SOFTMAX X")
print(sess.run(softmax_x))

[0.0, -1.0, 2.0, 3.0]
SOFTMAX X
[0.03467109 0.01275478 0.25618663 0.69638747]


In [71]:
pwd


'/content'

In [72]:
classes = ['dogs', 'cats']
num_classes = len(classes)
 
train_path='train'
 
# validation split
validation_size = 0.2
 
# batch size
batch_size = 16
 
data = dataset.read_train_sets(train_path, img_size, classes, validation_size=validation_size)


AttributeError: ignored

In [0]:
from keras.models import Sequential

Using TensorFlow backend.


In [0]:
from keras.layers import Convolution2D

In [0]:
from keras.layers import MaxPooling2D

In [0]:
from keras.layers import Flatten

In [0]:
from keras.layers import Dense

In [0]:
classifier=Sequential()
classifier.add(Convolution2D(32,(3,3),input_shape=(64,64,3),activation='relu'))

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
classifier.add(MaxPooling2D(pool_size=(2,2)))

In [0]:
classifier.add(Flatten())

In [0]:
classifier.add(Dense(units=128,activation='relu'))

In [0]:
classifier.add(Dense(units=1,activation='sigmoid'))

In [0]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [0]:
from keras.preprocessing.image import ImageDataGenerator

In [0]:
train_datagen=ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

In [0]:
test_datagen=ImageDataGenerator(rescale=1./255)

In [0]:
pwd


'/content'

test_datagen=ImageDataGenerator(rescale=1./255)


In [74]:
training_set=train_datagen.flow_from_directory(
   "/content/drive/My Drive/dogvscat/dataset/training_set",
    target_size=(64,64),
    batch_size=32,
    class_mode='binary')

FileNotFoundError: ignored

In [0]:
test_set=test_datagen.flow_from_directory(
    'dataset/test_set',
    target_size=(64,64),
    batch_size=32,
    class_mode='binary')

In [0]:
from IPython.display import display

In [0]:
from PIL import Image

In [0]:
classifier.fit_generator(training_set,steps_per_epoch=320,epochs=10,validation_data=test_set,validation_steps=800)

In [0]:
import numpy as np


In [0]:
from keras.preprocessing import image

In [0]:
test_im=image.load_img('random.jpeg',target_size=(64,64))

In [0]:
test_im=image.img_to_array(test_im)

In [0]:
test_im=np.expand_dims(test_im,axis=0)

In [0]:
result=classifier.predict_proba(test_im)
print(result)

In [0]:
training_set.class_indices

In [0]:
if result[0][0]>=0.5:
    prediction='dog'
else:
    prediction='cat'
print(result[0][0])

In [0]:
print(prediction)

In [0]:
test_ima=image.load_img('rand2.jpg',target_size=(64,64))

In [0]:
test_ima=image.img_to_array(test_ima)
test_ima=np.expand_dims(test_ima,axis=0)

In [0]:
resultt=classifier.predict_proba(test_ima)
print(resultt)

In [0]:
training_set.class_indices

In [0]:
if resultt[0][0]>=0.5:
    prediction='dog'
else:
    prediction='cat'
print(resultt[0][0])

In [0]:
print(prediction)

In [0]:
test_image=image.load_img('krishna.jpg',target_size=(64,64))

In [0]:
test_image=image.img_to_array(test_image)
test_image=np.expand_dims(test_image,axis=0)

In [0]:
resultkrishna=classifier.predict_proba(test_image)
print(resultkrishna)

In [0]:
test_image=image.load_img('krishnacat.jpg',target_size=(64,64))

In [0]:
test_image=image.img_to_array(test_image)
test_image=np.expand_dims(test_image,axis=0)

In [0]:
resultkrishna=classifier.predict(test_image)
print(resultkrishna)

In [0]:
test_image2=image.load_img('krishnadog.jpg',target_size=(64,64))

In [0]:
test_image2=image.img_to_array(test_image2)
test_image2=np.expand_dims(test_image2,axis=0)

In [0]:
res=classifier.predict(test_image2)
print(res)

In [0]:
test_image3=image.load_img('krishnacat.jpg',target_size=(64,64))

In [0]:
test_image3=image.img_to_array(test_image3)
test_image3=np.expand_dims(test_image3,axis=0)

In [0]:
resu=classifier.predict(test_image3)
print(resu)

In [0]:
test_image4=image.load_img('krishnaaa.jpg',target_size=(64,64))

In [0]:
test_image4=image.img_to_array(test_image4)
test_image4=np.expand_dims(test_image4,axis=0)

In [0]:
resul=classifier.predict(test_image4)
print(resu)

In [0]:
test_image5=image.load_img('krishna.jpg',target_size=(64,64))

In [0]:
test_image5=image.img_to_array(test_image5)
test_image5=np.expand_dims(test_image5,axis=0)

In [0]:
resultkrish=classifier.predict_proba(test_image5)
print(resultkrish)

In [0]:
test_image6=image.load_img('rama.jpg',target_size=(64,64))

In [0]:
test_image6=image.img_to_array(test_image6)
test_image6=np.expand_dims(test_image6,axis=0)

In [0]:
resultram=classifier.predict_proba(test_image6)
print(resultram)